# Generated by Django 2.2.5 on 2022-01-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Luxury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('veh_code', models.CharField(max_length=5)),
                ('veh_no', models.CharField(max_length=15)),
                ('luxury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Luxury')),
            ],
        ),
    ]
