# Generated by Django 2.2.5 on 2022-01-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Vehicles',
        ),
    ]
