# Generated by Django 2.2.5 on 2022-01-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20220117_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='veh_no',
            new_name='veh_price',
        ),
    ]
