# Generated by Django 2.2.5 on 2022-01-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20220117_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Luxury',
            new_name='Quality',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='luxury',
            new_name='quality',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='veh_code',
            new_name='vehicle_code',
        ),
        migrations.RenameField(
            model_name='vehicles',
            old_name='veh_price',
            new_name='vehicle_price',
        ),
    ]
