# Generated by Django 2.2.5 on 2022-01-18 10:48

from django.db import migrations, models
import vehicle.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20220117_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=vehicle.models.filepath),
        ),
    ]
