# Generated by Django 2.2.5 on 2022-01-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_vehicles_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='username',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
